// Gen IV TM/HM list — maps move slug (PokéAPI) to label (e.g. "TM01")
// Applies to Diamond / Pearl / Platinum / HeartGold / SoulSilver
// TM01–TM92 are identical across all Gen IV games.
// HM05 differs: Defog (DPPt) vs Whirlpool (HGSS) — both map to "HM05".

export const GEN4_MACHINES: Record<string, string> = {
  // TMs 01–50 (same slugs as Gen III, new numbers for TM51+)
  "focus-punch":    "TM01",
  "dragon-claw":    "TM02",
  "water-pulse":    "TM03",
  "calm-mind":      "TM04",
  "roar":           "TM05",
  "toxic":          "TM06",
  "hail":           "TM07",
  "bulk-up":        "TM08",
  "bullet-seed":    "TM09",
  "hidden-power":   "TM10",
  "sunny-day":      "TM11",
  "taunt":          "TM12",
  "ice-beam":       "TM13",
  "blizzard":       "TM14",
  "hyper-beam":     "TM15",
  "light-screen":   "TM16",
  "protect":        "TM17",
  "rain-dance":     "TM18",
  "giga-drain":     "TM19",
  "safeguard":      "TM20",
  "frustration":    "TM21",
  "solar-beam":     "TM22",
  "iron-tail":      "TM23",
  "thunderbolt":    "TM24",
  "thunder":        "TM25",
  "earthquake":     "TM26",
  "return":         "TM27",
  "dig":            "TM28",
  "psychic":        "TM29",
  "shadow-ball":    "TM30",
  "brick-break":    "TM31",
  "double-team":    "TM32",
  "reflect":        "TM33",
  "shock-wave":     "TM34",
  "flamethrower":   "TM35",
  "sludge-bomb":    "TM36",
  "sandstorm":      "TM37",
  "fire-blast":     "TM38",
  "rock-tomb":      "TM39",
  "aerial-ace":     "TM40",
  "torment":        "TM41",
  "facade":         "TM42",
  "secret-power":   "TM43",
  "rest":           "TM44",
  "attract":        "TM45",
  "thief":          "TM46",
  "steel-wing":     "TM47",
  "skill-swap":     "TM48",
  "snatch":         "TM49",
  "overheat":       "TM50",
  // TMs 51–92 (new in Gen IV)
  "roost":          "TM51",
  "focus-blast":    "TM52",
  "energy-ball":    "TM53",
  "false-swipe":    "TM54",
  "brine":          "TM55",
  "fling":          "TM56",
  "charge-beam":    "TM57",
  "endure":         "TM58",
  "dragon-pulse":   "TM59",
  "drain-punch":    "TM60",
  "will-o-wisp":    "TM61",
  "silver-wind":    "TM62",
  "embargo":        "TM63",
  "explosion":      "TM64",
  "shadow-claw":    "TM65",
  "payback":        "TM66",
  "recycle":        "TM67",
  "giga-impact":    "TM68",
  "rock-polish":    "TM69",
  "flash":          "TM70",
  "stone-edge":     "TM71",
  "avalanche":      "TM72",
  "thunder-wave":   "TM73",
  "gyro-ball":      "TM74",
  "swords-dance":   "TM75",
  "stealth-rock":   "TM76",
  "psych-up":       "TM77",
  "captivate":      "TM78",
  "dark-pulse":     "TM79",
  "rock-slide":     "TM80",
  "x-scissor":      "TM81",
  "sleep-talk":     "TM82",
  "natural-gift":   "TM83",
  "poison-jab":     "TM84",
  "dream-eater":    "TM85",
  "grass-knot":     "TM86",
  "swagger":        "TM87",
  "pluck":          "TM88",
  "u-turn":         "TM89",
  "substitute":     "TM90",
  "flash-cannon":   "TM91",
  "trick-room":     "TM92",
  // HMs (DPPt + HGSS share HM01–04, HM06–08; HM05 differs)
  "cut":            "HM01",
  "fly":            "HM02",
  "surf":           "HM03",
  "strength":       "HM04",
  "defog":          "HM05",  // DPPt
  "whirlpool":      "HM05",  // HGSS
  "rock-smash":     "HM06",
  "waterfall":      "HM07",
  "rock-climb":     "HM08",
};
