// Overrides for ugly auto-generated names
const LOCATION_OVERRIDES: Record<string, string> = {
  // ─── Kanto Routes ──────────────────────────────────────────────────────
  "kanto-route-1": "Route 1",
  "kanto-route-2": "Route 2",
  "kanto-route-3": "Route 3",
  "kanto-route-4": "Route 4",
  "kanto-route-5": "Route 5",
  "kanto-route-6": "Route 6",
  "kanto-route-7": "Route 7",
  "kanto-route-8": "Route 8",
  "kanto-route-9": "Route 9",
  "kanto-route-10": "Route 10",
  "kanto-route-11": "Route 11",
  "kanto-route-12": "Route 12",
  "kanto-route-13": "Route 13",
  "kanto-route-14": "Route 14",
  "kanto-route-15": "Route 15",
  "kanto-route-16": "Route 16",
  "kanto-route-17": "Route 17",
  "kanto-route-18": "Route 18",
  "kanto-route-19": "Route 19",
  "kanto-route-20": "Route 20",
  "kanto-route-21": "Route 21",
  "kanto-route-22": "Route 22",
  "kanto-route-23": "Route 23",
  "kanto-route-24": "Route 24",
  "kanto-route-25": "Route 25",
  // ─── Hoenn Routes ─────────────────────────────────────────────────────
  "hoenn-route-101": "Route 101",
  "hoenn-route-102": "Route 102",
  "hoenn-route-103": "Route 103",
  "hoenn-route-104": "Route 104",
  "hoenn-route-105": "Route 105",
  "hoenn-route-106": "Route 106",
  "hoenn-route-107": "Route 107",
  "hoenn-route-108": "Route 108",
  "hoenn-route-109": "Route 109",
  "hoenn-route-110": "Route 110",
  "hoenn-route-111": "Route 111",
  "hoenn-route-112": "Route 112",
  "hoenn-route-113": "Route 113",
  "hoenn-route-114": "Route 114",
  "hoenn-route-115": "Route 115",
  "hoenn-route-116": "Route 116",
  "hoenn-route-117": "Route 117",
  "hoenn-route-118": "Route 118",
  "hoenn-route-119": "Route 119",
  "hoenn-route-120": "Route 120",
  "hoenn-route-121": "Route 121",
  "hoenn-route-122": "Route 122",
  "hoenn-route-123": "Route 123",
  "hoenn-route-124": "Route 124",
  "hoenn-route-125": "Route 125",
  "hoenn-route-126": "Route 126",
  "hoenn-route-127": "Route 127",
  "hoenn-route-128": "Route 128",
  "hoenn-route-129": "Route 129",
  "hoenn-route-130": "Route 130",
  "hoenn-route-131": "Route 131",
  "hoenn-route-132": "Route 132",
  "hoenn-route-133": "Route 133",
  "hoenn-route-134": "Route 134",
  // ─── Hoenn Locations ──────────────────────────────────────────────────
  "hoenn-safari-zone": "Safari Zone",
  "hoenn-safari-zone-sw": "Safari Zone (SW)",
  "hoenn-safari-zone-se": "Safari Zone (SE)",
  "hoenn-safari-zone-nw": "Safari Zone (NW)",
  "hoenn-safari-zone-ne": "Safari Zone (NE)",
  "hoenn-mt-pyre": "Mt. Pyre",
  "hoenn-victory-road": "Victory Road",
  "hoenn-cave-of-origin": "Cave of Origin",
  "hoenn-sky-pillar": "Sky Pillar",
  "hoenn-desert-ruins": "Desert Ruins",
  "hoenn-island-cave": "Island Cave",
  "hoenn-ancient-tomb": "Ancient Tomb",
  "hoenn-underwater": "Underwater",
  // ─── Kanto Locations ──────────────────────────────────────────────────
  "kanto-safari-zone": "Safari Zone",
  "kanto-power-plant": "Power Plant",
  "kanto-seafoam-islands": "Seafoam Islands",
  "kanto-victory-road": "Victory Road",
  "kanto-cerulean-cave": "Cerulean Cave",
  "kanto-mt-moon": "Mt. Moon",
  "kanto-rock-tunnel": "Rock Tunnel",
  // ─── Sinnoh Routes ────────────────────────────────────────────────────
  "sinnoh-route-201": "Route 201",
  "sinnoh-route-202": "Route 202",
  "sinnoh-route-203": "Route 203",
  "sinnoh-route-204": "Route 204",
  "sinnoh-route-205": "Route 205",
  "sinnoh-route-206": "Route 206",
  "sinnoh-route-207": "Route 207",
  "sinnoh-route-208": "Route 208",
  "sinnoh-route-209": "Route 209",
  "sinnoh-route-210": "Route 210",
  "sinnoh-route-211": "Route 211",
  "sinnoh-route-212": "Route 212",
  "sinnoh-route-213": "Route 213",
  "sinnoh-route-214": "Route 214",
  "sinnoh-route-215": "Route 215",
  "sinnoh-route-216": "Route 216",
  "sinnoh-route-217": "Route 217",
  "sinnoh-route-218": "Route 218",
  "sinnoh-route-219": "Route 219",
  "sinnoh-route-220": "Route 220",
  "sinnoh-route-221": "Route 221",
  "sinnoh-route-222": "Route 222",
  "sinnoh-route-223": "Route 223",
  "sinnoh-route-224": "Route 224",
  "sinnoh-route-225": "Route 225",
  "sinnoh-route-226": "Route 226",
  "sinnoh-route-227": "Route 227",
  "sinnoh-route-228": "Route 228",
  "sinnoh-route-229": "Route 229",
  "sinnoh-route-230": "Route 230",
  // ─── Sinnoh Locations ─────────────────────────────────────────────────
  "mt-coronet": "Mt. Coronet",
  "mt-coronet-1f": "Mt. Coronet (1F)",
  "mt-coronet-2f": "Mt. Coronet (2F)",
  "mt-coronet-3f": "Mt. Coronet (3F)",
  "mt-coronet-4f": "Mt. Coronet (4F)",
  "mt-coronet-5f": "Mt. Coronet (5F)",
  "mt-coronet-6f": "Mt. Coronet (6F)",
  "mt-coronet-b1f": "Mt. Coronet (B1F)",
  "mt-coronet-exterior": "Mt. Coronet (Exterior)",
  "victory-road-sinnoh": "Victory Road",
  "victory-road-sinnoh-exterior": "Victory Road (Exterior)",
  "victory-road-sinnoh-1f": "Victory Road (1F)",
  "victory-road-sinnoh-2f": "Victory Road (2F)",
  "lake-valor": "Lake Valor",
  "lake-acuity": "Lake Acuity",
  "lake-verity": "Lake Verity",
  "spear-pillar": "Spear Pillar",
  "distortion-world": "Distortion World",
  "wayward-cave": "Wayward Cave",
  "wayward-cave-b1f": "Wayward Cave (B1F)",
  "eterna-forest": "Eterna Forest",
  "solaceon-ruins": "Solaceon Ruins",
  "iron-island": "Iron Island",
  "iron-island-b1f": "Iron Island (B1F)",
  "iron-island-b2f": "Iron Island (B2F)",
  "stark-mountain": "Stark Mountain",
  "stark-mountain-exterior": "Stark Mountain (Exterior)",
  "turnback-cave": "Turnback Cave",
  "floaroma-meadow": "Floaroma Meadow",
  "fuego-ironworks": "Fuego Ironworks",
  "trophy-garden": "Trophy Garden",
  "great-marsh": "Great Marsh",
  "snowpoint-temple": "Snowpoint Temple",
  "spring-path": "Spring Path",
  "sendoff-spring": "Sendoff Spring",
  "valley-windworks": "Valley Windworks",
  "old-chateau": "Old Chateau",
  "pal-park": "Pal Park",
  "pokemon-mansion-sinnoh": "Pokémon Mansion",
  // ─── Johto Routes (HGSS) ──────────────────────────────────────────────
  "johto-route-29": "Route 29",
  "johto-route-30": "Route 30",
  "johto-route-31": "Route 31",
  "johto-route-32": "Route 32",
  "johto-route-33": "Route 33",
  "johto-route-34": "Route 34",
  "johto-route-35": "Route 35",
  "johto-route-36": "Route 36",
  "johto-route-37": "Route 37",
  "johto-route-38": "Route 38",
  "johto-route-39": "Route 39",
  "johto-route-40": "Route 40",
  "johto-route-41": "Route 41",
  "johto-route-42": "Route 42",
  "johto-route-43": "Route 43",
  "johto-route-44": "Route 44",
  "johto-route-45": "Route 45",
  "johto-route-46": "Route 46",
  "johto-route-47": "Route 47",
  "johto-route-48": "Route 48",
  // ─── Johto Locations (HGSS) ───────────────────────────────────────────
  "mt-mortar": "Mt. Mortar",
  "mt-mortar-1f": "Mt. Mortar (1F)",
  "mt-mortar-2f": "Mt. Mortar (2F)",
  "mt-mortar-basement": "Mt. Mortar (Basement)",
  "mt-silver": "Mt. Silver",
  "mt-silver-exterior": "Mt. Silver (Exterior)",
  "mt-silver-1f": "Mt. Silver (1F)",
  "mt-silver-b1f": "Mt. Silver (B1F)",
  "victory-road-johto": "Victory Road",
  "victory-road-johto-1f": "Victory Road (1F)",
  "victory-road-johto-2f": "Victory Road (2F)",
  "victory-road-johto-3f": "Victory Road (3F)",
  "burned-tower": "Burned Tower",
  "burned-tower-1f": "Burned Tower (1F)",
  "burned-tower-b1f": "Burned Tower (B1F)",
  "whirl-islands": "Whirl Islands",
  "whirl-islands-ne": "Whirl Islands (NE)",
  "whirl-islands-nw": "Whirl Islands (NW)",
  "whirl-islands-se": "Whirl Islands (SE)",
  "whirl-islands-sw": "Whirl Islands (SW)",
  "whirl-islands-b1f": "Whirl Islands (B1F)",
  "whirl-islands-b2f": "Whirl Islands (B2F)",
  "ruins-of-alph": "Ruins of Alph",
  "dark-cave": "Dark Cave",
  "dark-cave-violet-city": "Dark Cave (Violet City side)",
  "dark-cave-blackthorn-city": "Dark Cave (Blackthorn side)",
  "ice-path": "Ice Path",
  "ice-path-1f": "Ice Path (1F)",
  "ice-path-b1f": "Ice Path (B1F)",
  "ice-path-b2f": "Ice Path (B2F)",
  "ice-path-b3f": "Ice Path (B3F)",
  "dragon-den": "Dragon's Den",
  "safari-zone-johto": "Safari Zone",
  "johto-safari-zone": "Safari Zone",
  "national-park": "National Park",
  "bug-catching-contest": "National Park (Bug-Catching Contest)",
  "slowpoke-well": "Slowpoke Well",
  "ilex-forest": "Ilex Forest",
  "union-cave": "Union Cave",
  "union-cave-1f": "Union Cave (1F)",
  "union-cave-b1f": "Union Cave (B1F)",
  "union-cave-b2f": "Union Cave (B2F)",
  "mt-moon-johto": "Mt. Moon",
  "sprout-tower": "Sprout Tower",
  "bell-tower": "Bell Tower",
  "tin-tower": "Tin Tower",
};

export function formatLocationSlug(slug: string): string {
  // Remove trailing -area suffix (e.g. "kanto-route-1-area" -> "kanto-route-1")
  const cleaned = slug.replace(/-area$/, "").replace(/-outside$/, "").replace(/-inside$/, "");

  if (LOCATION_OVERRIDES[cleaned]) {
    return LOCATION_OVERRIDES[cleaned];
  }

  // Generic transform: replace hyphens with spaces, capitalize each word
  return cleaned
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ")
    .replace(/^(Kanto|Hoenn|Johto|Sinnoh|Unova|Kalos|Alola|Galar|Paldea) /, "");
}
